import { describe, it, expect } from 'vitest'
import { markdownToTiptap, tiptapToMarkdown } from './tiptap-markdown'
import cases from './__fixtures__/adversarial-cases.json'

/**
 * Adversarial fuzz corpus generated by parallel case-generators (see the
 * fuzz-md-converter workflow). The contract we enforce is idempotency: once a
 * document has been normalized through one md -> tiptap -> md cycle, every
 * further cycle must be a no-op. That is what guarantees files don't churn on
 * the disk when merely opened.
 */
function norm(md: string): string {
  return tiptapToMarkdown(markdownToTiptap(md))
}

describe('adversarial idempotency fuzz', () => {
  const all: { category: string; md: string }[] = []
  for (const group of cases.categories) {
    for (const md of group.cases) all.push({ category: group.key, md })
  }

  it('has a non-trivial corpus', () => {
    expect(all.length).toBeGreaterThan(20)
  })

  for (let i = 0; i < (cases.categories as { key: string; cases: string[] }[]).length; i++) {
    const group = cases.categories[i]
    it(`stable fixed point for all ${group.key} cases`, () => {
      const failures: { md: string; once: string; twice: string }[] = []
      for (const md of group.cases) {
        const once = norm(md)
        const twice = norm(once)
        if (twice !== once) failures.push({ md, once, twice })
      }
      if (failures.length > 0) {
        const report = failures
          .map(
            (f) =>
              `INPUT:\n${JSON.stringify(f.md)}\nPASS1:\n${JSON.stringify(f.once)}\nPASS2:\n${JSON.stringify(f.twice)}`
          )
          .join('\n---\n')
        throw new Error(`${failures.length} non-idempotent case(s) in ${group.key}:\n${report}`)
      }
    })
  }
})
